export const opportunitiesData = [
  {
    id: 1,
    title: "Global Innovation Challenge 2025",
    organization: "Tech for Good Foundation",
    type: "Competition",
    location: "Global",
    deadline: "March 15, 2025",
    prize: "$50,000",
    tags: ["Technology", "Climate", "Innovation"],
    featured: true,
    status: "Active",
    applications: 245,
    views: 1250,
    datePosted: "January 10, 2025",
  },
  {
    id: 2,
    title: "Young Leaders Fellowship",
    organization: "Future Leaders Institute",
    type: "Fellowship",
    location: "New York, USA",
    deadline: "February 28, 2025",
    prize: "Full funding",
    tags: ["Leadership", "Development", "Networking"],
    featured: false,
    status: "Draft",
    applications: 89,
    views: 567,
    datePosted: "January 8, 2025",
  },
  {
    id: 3,
    title: "Sustainable Business Accelerator",
    organization: "Green Ventures",
    type: "Accelerator",
    location: "London, UK",
    deadline: "April 10, 2025",
    prize: "€100,000",
    tags: ["Sustainability", "Business", "Startups"],
    featured: true,
    status: "Active",
    applications: 156,
    views: 892,
    datePosted: "January 5, 2025",
  },
  {
    id: 4,
    title: "Digital Arts Residency Program",
    organization: "Creative Hub",
    type: "Residency",
    location: "Berlin, Germany",
    deadline: "January 30, 2025",
    prize: "Studio space + stipend",
    tags: ["Arts", "Digital", "Creative"],
    featured: false,
    status: "Closed",
    applications: 234,
    views: 1100,
    datePosted: "November 15, 2024",
  },
  {
    id: 5,
    title: "Social Impact Scholarship",
    organization: "Impact University",
    type: "Scholarship",
    location: "Various",
    deadline: "March 1, 2025",
    prize: "Full tuition",
    tags: ["Education", "Social Impact", "Scholarship"],
    featured: false,
    status: "Active",
    applications: 78,
    views: 445,
    datePosted: "December 20, 2024",
  },
  {
    id: 6,
    title: "Healthcare Innovation Grant",
    organization: "Medical Research Foundation",
    type: "Grant",
    location: "Global",
    deadline: "February 15, 2025",
    prize: "$75,000",
    tags: ["Healthcare", "Innovation", "Global Health"],
    featured: false,
    status: "Active",
    applications: 156,
    views: 892,
    datePosted: "January 5, 2025",
  },
]

export const categoriesData = [
  { name: "Scholarships", href: "/categories/scholarships" },
  { name: "Competitions", href: "/categories/competitions" },
  { name: "Fellowships", href: "/categories/fellowships" },
  { name: "Grants", href: "/categories/grants" },
  { name: "Accelerators", href: "/categories/accelerators" },
  { name: "Residencies", href: "/categories/residencies" },
]

export const categoryTypes = ["All", "Competition", "Fellowship", "Scholarship", "Grant", "Accelerator", "Residency"]

export const statsData = [
  { label: "Active Opportunities", value: "2,500+", icon: "TrendingUp" },
  { label: "Success Stories", value: "15,000+", icon: "Star" },
  { label: "Total Funding", value: "$50M+", icon: "Award" },
  { label: "Global Reach", value: "150+", icon: "Globe" },
]
